import {
  Aim,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ChatRound,
  Check,
  CircleCheck,
  Clock,
  Close,
  Collection,
  CopyDocument,
  Cpu,
  DataBoard,
  Delete,
  Document,
  Download,
  EditPen,
  Film,
  Folder,
  FolderOpened,
  Grid,
  Hide,
  Histogram,
  Lightning,
  Link,
  Loading,
  Lock,
  Paperclip,
  Picture,
  Plus,
  Promotion,
  Reading,
  Refresh,
  RefreshLeft,
  Search,
  Setting,
  Star,
  Tools,
  Upload,
  User,
  VideoCamera,
  VideoPlay,
  View,
  Warning,
} from '@element-plus/icons-vue'
import {
  Activity,
  Archive,
  AtSign,
  Bot,
  Braces,
  Brain,
  Calculator,
  Cat,
  Circle,
  CircleX,
  Code,
  Code2,
  Database,
  Dices,
  Eraser,
  FilePlus2,
  FolderSearch,
  GitBranch,
  Globe,
  Hash,
  LayoutTemplate,
  Lightbulb,
  ListTree,
  PackageCheck,
  Palette,
  PawPrint,
  Radio,
  Regex,
  Rocket,
  Save,
  ScanText,
  ScrollText,
  Server,
  Shield,
  Sparkles,
  Square,
  Table,
  Type,
  ZapOff,
  MoreHorizontal,
  Terminal,
  Webhook,
  Mail,
} from './custom'

/**
 * 统一图标模块（图标统一）。
 *
 * <p>全站图标只从本模块取：Element Plus 图标 re-export + 缺失图标自绘，保证风格统一。
 * 用户决策：统一到 EP 图标库（与 EP 组件同源）；EP 缺失的图标（Bot/Brain/Sparkles/PawPrint/
 * Rocket/GitBranch 等）在 `./custom` 自绘（数据取自 lucide path，props 与 lucide 兼容）。
 *
 * <p>本模块保持 lucide 命名导出（`<Xxx />` 模板零改动），EP 库有的直接映射、
 * 没有的走自绘。所有消费方统一 `import { Xxx } from '@/components/common/icons'`。
 */
export {
  // —— EP 同名直接导出 ——
  Check,
  CircleCheck,
  Clock,
  Cpu,
  Delete,
  Download,
  Film,
  Folder,
  Lock,
  Paperclip,
  Plus,
  Search,
  Star,
  Upload,
  User,
  ArrowLeft,
  ArrowRight,
  // —— EP 映射导出（lucide 名 → EP 名）——
  Warning as AlertTriangle,
  Histogram as BarChart3,
  Reading as BookOpen,
  ArrowDown as ChevronDown,
  CopyDocument as Copy,
  Aim as Crosshair,
  Document as File,
  Picture as FileImage,
  VideoCamera as FileVideo,
  Document as FileText,
  FolderOpened as FolderOpen,
  Picture as Image,
  Picture as ImageIcon,
  Collection as Layers,
  DataBoard as LayoutDashboard,
  Grid as LayoutGrid,
  Loading as Loader2,
  Link as Link2,
  ChatRound as MessageSquare,
  EditPen as Pencil,
  VideoPlay as Play,
  Promotion as Send,
  Setting as Settings,
  Tools as Wrench,
  Delete as Trash2,
  Close as X,
  Lightning as Zap,
  View as Eye,
  Hide as EyeOff,
  Refresh as RefreshCw,
  RefreshLeft as RotateCcw,
  // —— 自绘图标（EP 缺失，行为与 lucide 兼容）——
  Activity,
  Archive,
  AtSign,
  Bot,
  Braces,
  Brain,
  Calculator,
  Cat,
  Circle,
  CircleX,
  Code,
  Code2,
  Database,
  Dices,
  Eraser,
  FilePlus2,
  FolderSearch,
  GitBranch,
  Globe,
  Hash,
  LayoutTemplate,
  Lightbulb,
  ListTree,
  MoreHorizontal,
  PackageCheck,
  Palette,
  PawPrint,
  Radio,
  Regex,
  Rocket,
  Save,
  ScanText,
  ScrollText,
  Server,
  Shield,
  Sparkles,
  Square,
  Table,
  Type,
  ZapOff,
  Terminal,
  Webhook,
  Mail,
}
